substitutions:
  board_platform: ESP8266
  board_type: d1_mini
  devicename: audio_doorbell_top_floor
  hostname: top floor chime
  devicestatusname: audio_doorbell_top_floor_status
  staticip: 192.168.86.239
  apssid: esphome_aud_doorbell_top_flr
  wifigateway: 192.168.86.1
  subnet: 255.255.255.0
  tx_pin: D6
  rx_pin: D5

esphome:
  name: $devicename
  platform: $board_platform
  board: $board_type

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pwd
  - ssid: !secret wifi_ssid_backup
    password: !secret wifi_pwd_backup
  manual_ip:
    static_ip: $staticip
    gateway: $wifigateway
    subnet: $subnet
  ap: #Settings for captive portal
    ssid: $apssid
    password: !secret esphome_appassword
captive_portal: # AP in case WiFi connection fails

# Enable logging
logger:

# Enable OTA firmware update
ota:

switch:      
  - platform: restart
    name: $hostname restart

binary_sensor:
  - platform: status
    name: $devicestatusname

# dfplayer #######################################################
# on SD card:
# westminster chimes 1

uart:
  tx_pin: $tx_pin
  rx_pin: $rx_pin
  baud_rate: 9600

dfplayer:
  on_finished_playback:
    then:
      logger.log: 'Playback finished event'

api:
  services:
  - service: dfplayer_play
    variables:
      file: int
    then:
      - dfplayer.play: !lambda 'return file;'

  - service: dfplayer_set_volume
    variables:
      volume: int
    then:
      - dfplayer.set_volume: !lambda 'return volume;'

  - service: dfplayer_reset
    then:
      - dfplayer.reset

  - service: dfplayer_stop
    then:
      - dfplayer.stop